fail on error

diff --git a/.github/workflows/deploy-backend.yml b/.github/workflows/deploy-backend.yml
--- a/.github/workflows/deploy-backend.yml
+++ b/.github/workflows/deploy-backend.yml
@@ -44,5 +44,12 @@ jobs:
         EOF
     - name: Health Check
       run: |
-        curl -X GET http://16.171.224.57:3000/health
+        RESPONSE=$(curl -s -o response.json -w "%{http_code}" http://16.171.224.57:3000/health)
+          echo "Response Code: $RESPONSE"
+          cat response.json  # Print the response body for debugging
+
+          if [[ "$RESPONSE" -ne 200 ]]; then
+            echo "Health check failed!"
+            exit 1  # Fail the workflow if response is not 200
+          fi
 
